#!/usr/bin/env bash
# =============================================================================
# City Agent Aria — one-command installer
#
#   sudo bash install.sh
#
# Installs Docker, generates internal secrets, writes .env.prod, builds, and
# starts everything. TWO modes:
#
#   [1] Behind my own proxy (Nginx Proxy Manager / external nginx)  ← DEFAULT
#       Asks: super-admin email, super-admin PASSWORD (your choice),
#             OpenRouter key, HOST PORT, public URL.
#       Exposes the app on http://THIS_SERVER:<PORT>. YOUR proxy adds HTTPS.
#
#   [2] Built-in nginx + automatic HTTPS (Let's Encrypt)
#       Asks: domain, email, OpenRouter key, super-admin email + PASSWORD.
#       Serves HTTPS itself on 80/443.
#
# Non-interactive: pass any answer as an env var, e.g.
#   sudo MODE=npm SUPERADMIN_EMAIL=admin@co.com SUPERADMIN_PASSWORD=... \
#        OPENROUTER_API_KEY=sk-or-... APP_PORT=8082 PUBLIC_URL=https://aria.co bash install.sh
# =============================================================================
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
say() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
[ "$(id -u)" = 0 ] || die "Run with sudo:  sudo bash install.sh"

prompt() {  # prompt VAR "Question" "default"
  local var="$1" q="$2" def="${3:-}" cur="${!1:-}"
  [ -n "$cur" ] && return 0
  if [ -n "$def" ]; then read -rp "$q [$def]: " val; val="${val:-$def}"
  else read -rp "$q: " val; fi
  [ -n "$val" ] || die "$var is required"
  printf -v "$var" '%s' "$val"
}
prompt_pw() {  # hidden password with confirm
  local var="$1" cur="${!1:-}"
  [ -n "$cur" ] && return 0
  local p1 p2
  read -rsp "Super-admin password (choose your own): " p1; echo
  read -rsp "Confirm password: " p2; echo
  [ "$p1" = "$p2" ] || die "passwords do not match"
  [ ${#p1} -ge 8 ] || die "password must be at least 8 characters"
  printf -v "$var" '%s' "$p1"
}

# ---- mode ----
say "City Agent Aria installer"
if [ -z "${MODE:-}" ]; then
  echo "  How will HTTPS be handled?"
  echo "    1) Behind my own proxy (Nginx Proxy Manager / external nginx)  [default]"
  echo "    2) Built-in nginx + automatic Let's Encrypt HTTPS"
  read -rp "  Choose 1 or 2 [1]: " m; MODE=$([ "${m:-1}" = 2 ] && echo letsencrypt || echo npm)
fi

# ---- docker ----
if ! command -v docker >/dev/null 2>&1; then say "Installing Docker"; curl -fsSL https://get.docker.com | sh; fi
systemctl enable --now docker >/dev/null 2>&1 || true
DC="docker compose"; $DC version >/dev/null 2>&1 || die "docker compose v2 not available"

rnd() { openssl rand -hex "${1:-32}"; }

# ---- common inputs ----
prompt SUPERADMIN_EMAIL   "Super-admin login email"
prompt_pw SUPERADMIN_PASSWORD
prompt OPENROUTER_API_KEY "OpenRouter API key (sk-or-...)"

if [ "$MODE" = npm ]; then
  prompt APP_PORT   "Host port to expose the app on (your proxy forwards here)" "8082"
  prompt PUBLIC_URL "Public URL your proxy serves (https://aria.cityxyz.com.mm)"
  COMPOSE=docker-compose.npm.yml
else
  prompt DOMAIN "Domain to serve on (e.g. aria.cityxyz.com.mm)"
  prompt EMAIL  "Email for Let's Encrypt"
  PUBLIC_URL="https://${DOMAIN}"; COMPOSE=docker-compose.prod.yml
fi

# ---- .env.prod ----
say "Writing .env.prod"
JWT_SECRET="${JWT_SECRET:-$(rnd 32)}"                 # internal — auto
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(rnd 16)}"   # internal — auto
cat > .env.prod <<EOF
# generated by install.sh $(date -u +%FT%TZ) — do not commit
APP_ENV=production
PUBLIC_URL=${PUBLIC_URL}
CORS_ALLOW_ORIGINS=

OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
JWT_SECRET=${JWT_SECRET}

SUPERADMIN_EMAIL=${SUPERADMIN_EMAIL}
SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}

DATABASE_URL=postgresql://docsensei:${POSTGRES_PASSWORD}@db:5432/docsensei
POSTGRES_USER=docsensei
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=docsensei
PG_MAX_CONNECTIONS=200

WEB_CONCURRENCY=4
DB_POOL_MIN=2
DB_POOL_MAX=10
LLM_MAX_CONCURRENCY=30
INGEST_IN_API=0
WORKER_VISION_WORKERS=12
APP_PORT=${APP_PORT:-8082}

STORAGE=local
AUTO_QA_SERVE_ENABLED=1
CHAT_MODEL=google/gemini-3.1-flash-lite
INGEST_MODEL=openrouter/google/gemini-3.1-flash-lite
EOF
chmod 600 .env.prod

# ---- build ----
say "Building the app image (first build ~5-10 min)"
BUILD_SHA="$(date +%s | sha1sum | cut -c1-7)" BUILD_DATE="$(date +%F)" $DC -f "$COMPOSE" --env-file .env.prod build

# ---- start ----
if [ "$MODE" = npm ]; then
  say "Starting app on host port ${APP_PORT}"
  $DC -f "$COMPOSE" --env-file .env.prod up -d
else
  # (built-in nginx path: bootstrap http → cert → swap to https — see prod compose)
  say "Starting core services (http bootstrap)"
  mkdir -p deploy
  cat > deploy/nginx.active.conf <<EOF
upstream aria_app { server app:8077; }
server { listen 80; server_name ${DOMAIN}; client_max_body_size 512m;
  location /.well-known/acme-challenge/ { root /var/www/certbot; }
  location / { proxy_pass http://aria_app; proxy_set_header Host \$host; proxy_set_header X-Forwarded-Proto \$scheme; proxy_buffering off; proxy_read_timeout 3600s; proxy_http_version 1.1; } }
EOF
  $DC -f "$COMPOSE" --env-file .env.prod up -d db app worker nginx
  say "Requesting HTTPS certificate for ${DOMAIN}"
  $DC -f "$COMPOSE" --env-file .env.prod run --rm --entrypoint certbot certbot certonly --webroot -w /var/www/certbot \
      -d "${DOMAIN}" --email "${EMAIL}" --agree-tos --no-eff-email --non-interactive \
    || die "Cert failed — check DNS A record for ${DOMAIN} points here and ports 80/443 are open."
  sed "s/__DOMAIN__/${DOMAIN}/g" deploy/nginx.ssl.tmpl > deploy/nginx.active.conf
  $DC -f "$COMPOSE" --env-file .env.prod exec -T nginx nginx -s reload
  $DC -f "$COMPOSE" --env-file .env.prod up -d certbot
fi

# ---- wait ----
say "Waiting for the app"
for i in $(seq 1 60); do
  if $DC -f "$COMPOSE" --env-file .env.prod exec -T app python -c "import urllib.request;urllib.request.urlopen('http://localhost:8077/api/version')" >/dev/null 2>&1; then echo "  app up"; break; fi
  sleep 3; [ "$i" = 60 ] && die "app did not start — check: $DC -f $COMPOSE logs app"
done

# ---- done ----
printf '\n\033[1;32m════════════════════════════════════════════════════\n  City Agent Aria is LIVE\n════════════════════════════════════════════════════\033[0m\n'
if [ "$MODE" = npm ]; then
  IP="$(curl -s ifconfig.me 2>/dev/null || echo YOUR_SERVER_IP)"
  printf '  App (http):     http://%s:%s   ← point your proxy here\n' "$IP" "${APP_PORT}"
  printf '  Public URL:     %s   (set in your proxy)\n' "$PUBLIC_URL"
  printf '\n  In Nginx Proxy Manager → Proxy Host:\n'
  printf '   • Forward: http · %s · port %s   (Websockets ON)\n' "$IP" "${APP_PORT}"
  printf '   • SSL: request Let'"'"'s Encrypt cert, Force SSL\n'
  printf '   • Advanced tab, paste:\n'
  printf '       proxy_buffering off; proxy_read_timeout 3600s;\n'
  printf '       proxy_send_timeout 3600s; client_max_body_size 512m;\n'
else
  printf '  URL:            %s\n' "$PUBLIC_URL"
fi
printf '\n  Super-admin:    %s\n' "$SUPERADMIN_EMAIL"
printf '  Password:       (the one you chose)\n'
printf '\n  Manage:  docker compose -f %s [ps|logs -f|restart]\n\n' "$COMPOSE"
